const products = [
  {
    id: 1,
    name: "iPhone 14 pro",
    desc: "6.1-inch display",
    price: 999,
    img: "https://tse4.mm.bing.net/th?id=OIP.V_M3E6rGGHhAm1gZF4DdBQHaHa&pid=Api&P=0&h=180",
    memory: "256 GB ROM",
    display: "15.49 cm (6.1 inch) Super Retina XDR Display",
    camera: "48MP + 12MP + 12MP | 12MP Front Camera",
    processor: "A16 Bionic Chip, 6 Core Processor Processor",
  },
  {
    id: 2,
    name: "iPhone 14",
    desc: "5.4-inch display",
    price: 799,
    img: "https://tse1.mm.bing.net/th?id=OIP.BBjeLwCpYb22yGXbVwO6ugHaHa&pid=Api&P=0&h=180",
    memory: "128 GB ROM",
    display: "15.49 cm (6.1 inch) Super Retina XDR Display",
    camera: "12MP + 12MP | 12MP Front Camera",
    processor: "A15 Bionic Chip, 6 Core Processor Processor",
  },
  {
    id: 3,
    name: "Galaxy S23 ultra",
    desc: "6.5-inch display",
    price: 499,
    img: "https://tse2.mm.bing.net/th?id=OIP.E_NUOR-N7YRtQxXe1usphAHaHa&pid=Api&P=0&h=180",
    memory: "12 GB RAM | 256 GB ROM",
    display: "17.27 cm (6.8 inch) Quad HD+ Display",
    camera: "200MP + 10MP + 12MP + 10MP | 12MP Front Camera",
    processor: "Qualcomm Snapdragon 8 Gen 2 Processor",
  },
  {
    id: 4,
    name: "OnePlus 9 Pro",
    desc: "6.7-inch display",
    price: 399,
    img: "https://media.whatprice.com/wp-content/uploads/2021/03/24053811/oneplus-9pro-pine-green-1261x1536.jpg",
    memory: "12 GB RAM | 256 GB ROM",
    display: "17.02 cm (6.7 inch) Display",
    camera: "48MP Rear Camera",
    processor: "Qualcomm® Snapdragon™ 888",
  },
];

module.exports = products;
